<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pnp_cobot_bringup</name>
  <version>0.0.0</version>
  <description>Launch files and basic nodes for starting PnP Cobot robot drivers and capabilities</description>
  <maintainer email="sroyy57@gmail.com">Souvik Roy</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller_manager_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>pnp_cobot_gazebo</exec_depend>
  <exec_depend>pnp_cobot_moveit_config</exec_depend>
  <exec_depend>pnp_cobot_mtc_demos</exec_depend>
  <exec_depend>pnp_cobot_mtc_pick_place_demo</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
